###########################################################
##################  boolean         #######################
###########################################################


[bool]

[bool.are_you_functional]
prompt_type = "boolean"
name = "are_you_functional"
prompt = "Have you been functional this week?"
description = "Are you exercising, cooking, and meeting objectives this week?"

[bool.do_you_feel_pleasure]
prompt_type = "boolean"
name = "do_you_feel_pleasure"
prompt = "Are you able to feel pleasure with activities?"
description = "Do you feel pleasure from coding, YouTube, guitar, and DotA2?"

[bool.talking_to_friends]
prompt_type = "boolean"
name = "talking_to_friends"
prompt = "Are you talking to your friends?"
description = "In the last week, have you called or texted your friends?"

[bool.cooking_today]
prompt_type = "boolean"
name = "cooking_today"
prompt = "Are you cooking today?"
description = "What is your plan for groceries, mealprep, and cooking today?"

[bool.exercise_today]
prompt_type = "boolean"
name = "exercising_today"
prompt = "Are you exercising today?"
description = "Are you going to walk, run, or lift today?"

[bool.schedule_appts]
prompt_type = "boolean"
name = "uptodate_scheduled_appts"
prompt = "Are you up-to-date on (re)scheduling appointments?"
description = "Drs. Tramatozzi and Welch, MVP Erin, CCHS, SereneMind?"


###########################################################
##################  choice          #######################
###########################################################

#[choice]

###########################################################
##################  multichoice     #######################
###########################################################

#[multichoice]

###########################################################
##################  singleline      #######################
###########################################################

[singleline]

[singleline.next_meeting]
prompt_type = "singleline"
name = "next_meeting"
prompt = "When is your next meeting? Do you need to prepare?"
description = "U.Del lecture? N.A. meeting? Professional?"


###########################################################
##################  multiline       #######################
###########################################################

[multiline] # list

[multiline.worries_me_today]
prompt_type = "multiline"
name = "what_worries_me_today"
prompt = "What worries you today?"
description = "What subjects are on your mind today? (past events, trauma, anxieties)"

[multiline.looking_forward_to]
prompt_type = "multiline"
name = "looking_forward_to"
prompt = "What are you looking forward to?"
description = "Events, food, shopping, milestone?"

# [multiline.how_much_time]
# prompt_type = "multiline"
# name = "how_much_time"
# prompt = "How much time can you budget to each item today?"
# description = "For each item on your todo list, how much time does each require?"

[multiline.lieing_to_myself]
prompt_type = "multiline"
name = "lieing_to_myself"
prompt = "What lies are you telling yourself?"
description = "1. What's going wrong? 2. What excuses are there? 3. Assess the lies you believe"

[multiline.what_do_I_need_to_hear]
prompt_type = "multiline"
name = "what_do_I_need_to_hear"
prompt = "What do I need to hear today?"
description = "Write down some words of encouragement. Try to focus on today"

[multiline.what_options_today]
prompt_type = "multiline"
name = "what_options_today"
prompt = "What options do I have today?"
description = "[rethink]: I'm lucky that I have options to choose"

[multiline.what_am_I_unsure_about]
prompt_type = "multiline"
name = "what_am_I_unsure_about"
prompt = "What am I confused or unsure about today?"
description = "Can you talk yourself through these uncertainties?"

[multiline.envision_success]
prompt_type = "multiline"
name = "envision_success"
prompt = "Use Reddit/YouTube to envision success. What does it look like?"
description = "Is it a place? An activity? A mindset?"

[multiline.blocking_issues]
prompt_type = "multiline"
name = "blocking_issues"
prompt = "What issues are blocking progress?"
description = "Either mental-health or work, what are you blockers?"

[multiline.red_flags]
prompt_type = "multiline"
name = "red_flags"
prompt = "What red flags do you see?"
description = "Are you slowing down on exercise, cooking, groceries, journaling? NOTE IT."

[multiline.what_assumptions_matter_today]
prompt_type = "multiline"
name = "what_assumptions_matter_today"
prompt = "What assumptions matter *today*?"
description = "Take a glance at assumptions in the last week. Which ones matter today?"

[multiline.possessions_im_grateful_for]
prompt_type = "multiline"
name = "possessions_im_grateful_for"
prompt = "What possessions are you grateful for?"
description = "Consider your worldly possessions. Which ones are you grateful for this week and why?"



[multiline.new_blog_post_titles]
prompt_type = "multiline"
name = "new_blog_post_titles"
prompt = "Write a new title/topic for a blog post"
description = "Consider existing tags, current events, and technical topics."

[multiline.well_rounded]
prompt_type = "multiline"
name = "well_rounded"
prompt = "How can you become a more well-rounded individual?"
description = "Health, habits, and happiness. Knowledge, books, interests."

[multiline.same_things]
prompt_type = "multiline"
name = "same_things"
prompt = "How can you become better at the same things you focus on?"
description = "[Biochemistry], programming, research"

[multiline.positive_in_last_week]
prompt_type = "multiline"
name = "positive_in_last_week"
prompt = "Name positive things that happened in the last week."
description = "What happened? How did it make you feel? What positive things do you want to happen?"

[multiline.repeating_positive_habits]
prompt_type = "multiline"
name = "repeating_positive_habits"
prompt = "State some positive habits you're noticing are planting roots..."
description = "[pause]: What positive habits are forming? Which are not?"


[multiline.repeating_negative_habits]
prompt_type = "multiline"
name = "repeating_negative_habits"
prompt = "State some negative habits/thoughts that are forming..."
description = "[pause]: What negative habits or thoughts are reinforcing poor self-image"

[multiline.approaching_deadlines]
prompt_type = "multiline"
name = "approaching_deadlines"
prompt = "What deadlines are approaching?"
description = "[review]: Review your phone calendar for the next two months. What deadlines or milestones need attention this week?"

[multiline.diffuse_triggers]
prompt_type = "multiline"
name = "diffuse_triggers"
prompt = "What triggers are coming up? How have/should you diffuse them?"
description = "What activities are helping consistently? What do you notice about these triggering events/feelings?"

[multiline.rewards_today]
prompt_type = "multiline"
name = "rewards_today"
prompt = "What rewards can you plan for this week/milestone? How will you achieve the reward?"
description = "What are the small rewards vs big ones? Can you push the timing of the reward off?"

###########################################################
##################  text            #######################
###########################################################

[text]

[text.avoiding]
prompt_type = "text"
name = "avoiding"
prompt = "What difficulty are you avoiding?"
description = "[pause]: What past or future challenges (work/mental) aren't being addressed?"

[text.life_story_last_month]
prompt_type = "text"
name = "life_story_last_month"
prompt = "In your life's story, where did you leave things last month?"
description = "[pause]: Think about your life's story. Write an abridged version in *scratch*. Where does last month's chapter fit in?"

[text.life_story_this_month]
prompt_type = "text"
name = "life_story_this_month"
prompt = "In your life's story, how will you make progress this month?"
description = "[pause]: Think about it. Where does *this* month fit in?"


[text.daily_note_mom]
prompt_type = "text"
name = "daily_note_mom"
prompt = "Write a note for mom."
description = "[pause]: think about her helpfulness, cheerfulness, smile, humor, and good nature"

[text.daily_note_dad]
prompt_type = "text"
name = "daily_note_dad"
prompt = "Write a note for dad."
description = "[pause]: think about his encouragement, discipline, routines, and conversations"

[text.opportunity_costs]
prompt_type = "text"
name = "opportunity_costs"
prompt = "What are you investing time/effort into today?"
description = "Who is the source? How difficult is the task?"

[text.negative_event]
prompt_type = "text"
name = "negative_event"
prompt = "Name a negative event in your life. What did you miss?"
description = "What could you have done differently? What does hindsight show? How did it effect you?"

########################################################### 
################## belief           #######################
###########################################################

#[belief]


########################################################### 
################## belieflist       #######################
###########################################################

[belieflist]

[belieflist.healthy_beliefs]
prompt_type = "belief"
name = "healthy_beliefs"
prompt = "What assumptions can I make that are positive?"
description = "Good assumptions are likely to be true (1:10). Topics include society, state of mind, steps in the journey, and better self image"
scale_label = "How strong is this belief?"
reason_label = "What is the assumption?"

[belieflist.unhealthy_beliefs]
prompt_type = "belief"
name = "unhealthy_beliefs"
prompt = "What bad assumptions am I making?"
description = "Bad assumptions aren't just unlikely to be true (1:10). They involve speculation and delusional or paranoid thinking or extend to topics where too much uncertainty clouds the effectiveness of the belief and its application to my life."
scale_label = "How strong is this belief?"
reason_label = "What is the assumption?"


#        task vs goals : time management and planning topics

[belieflist.good_work_assumptions]
prompt_type = "belief"
name = "good_work_task_goal_assumptions"
prompt = "What are some good assumptions I can make to simplify my efforts/work?"
description = "Good assumptions simplify your efforts and clarify objectives. Constrain your efforts and the objectives of a goal with assumptions."
scale_label = "How important is this statement/question to the goal at hand?"
reason_label = "What is the assumption or question? Where does it lead?"

[belieflist.bad_work_assumptions]
prompt_type = "belief"
name = "bad_work_task_goal_assumptions"
prompt = "What weak assumptions are leading to wasted effort? Focus on statement, not remedy."
description = "Bad assumptions provide unneeded structure, or provide options that add complexity in the approach towards objectives. Focus on stating the nature of these time wasters, rather than fixing them just yet."
scale_label = "How much is this statement/question detracting from the goals at hand?"
reason_label = "What is the assumption or question? Where does it lead?"


[belieflist.time_management]
prompt_type = "belief"
name = "time_management"
prompt = "Create a time budget/schedule for todays tasks. (not goals)"
description = "What tasks do you have? How much time does each need?"
scale_label = "How many hours?"
reason_label = "Describe your task"

