[quotes]
[quotes.when_in_doubt]
author = "Garrison Keillor"
quote = "When in doubt, look intelligent"

[quotes.young_writer]
author = "Garrison Keillor"
quote = "A young writer is easily tempted by the allusive and ethereal and ironic and reflective, but the declarative is at the bottom of most good writing"

[quotes.some_luck_lies]
author = "Garrison Keillor"
quote = "Some luck lies in not getting what you thought you wanted but getting what you have, which once you have got it you may be smart enough to see is what you would have wanted had you known."

[quotes.thank_you_dear_god]
author = "Garrison Keillor"
quote = "Thank you dear God for this good life, and forgive us if we do not love it enough. Thank you for the rain. And for the chance to wake up in three hours and go fishing. I thank you for that now, because I won't feel so thankful then."

[quotes.welcome_to_lake_wobegon]
author = "Garrison Keillor"
quote = "Welcome to Lake Wobegon, where all the women are strong, all the men are good-looking, and all the children are above average."

[quotes.nothing_done_for_children]
author = "Garrison Keillor"
quote = "Nothing you do for children is ever wasted"

[quotes.campfires_of_gentle_people]
author = "Garrison Keillor"
quote = "Even in a time of elelphantine vanity and greed, one never has to look far for the campfires of gentle people."

[quotes.sitting_in_a_garage]
author = "Garrison Keillor"
quote = "Anyone who thinks sitting in a church makes you a Christian must also think that sitting in a garage can make you a car."

[quotes.see_what_happens]
author = "Mandy Hale"
quote = "You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens."


[quotes.one_small_positive_thought]
author = "Dalai Lama"
quote = "Just one small positive thought in the morning can change your whole day."

[quotes.nature_does_not_hurry]
author = "Unknown"
quote = "Nature does not hurry. Yet, everything is accomplished."


[quotes.courage_to_face_things]
author = "I Ching"
quote = "It is only when we have the courage to face things exactly as they are, without any self-deception or illusion, that a light will develop out of events, by which the path to success may be recognized."


[quotes.go_with_the_flow]
author = "Lao Tzu"
quote = "**Life is a series** of natural and spontaneous **changes**. Don't resist them - that only creates sorrow. **Let things flow naturally forward in whatever way they like.**"


[quotes.ten_thousand_beings]
author = "i ching - Alfred Huang"
quote = "Ten thousand beings carry yin and embrace yang; By blending their energies they achieve harmony. Therefore existence and nonexistence produce each other. Difficulty and ease complement each other. Long and short contrast with each other. High and low rely on each other. Sound and voice harmonize with each other."


[quotes.the_wise_man]
author = "i ching - Hellmut Wilhelm"
quote = "The wise man gladly leaves fame to others. He does not seek to have credited to himself things that stand accomplished, but hopes to release active forces; that is, he completes his works in such a manner that they may bare fruit for the future."

[quotes.regret_vanishes]
author = "i ching - Alfred Huang"
quote = "Regret vanishes. Lose or gain, stop worrying. Going forward; good fortune. Nothing is unfavorable. Win or lose, stop worrying. To proceed will afford ground for congratulations."

[quotes.to_become_strong]
author = "i ching - Anonymouse"
quote = "To become strong, a man's life needs the limistations ordained by duty and voluntarily (be) accepted. The individual attains significance as a free spirit only by surrounding himself with these limitations and by determining for himself what his duty is."

[quotes.he_who_in_times]
author = "i ching - Fu Hsi"
quote = "He who in times of extraordinary salience of small things does not know how to call a halt, but restlessly seeks to press on and on, draws upon himself misfortune at the hands of gods and men, because he deviates from the order of nature."

[quotes.before_the_beginning]
author = "i ching - Anonymous"
quote = "Before the beginning of great brilliance, there must be chaos. Before a brilliant person begins something great, they must look foolish in the crowd."


[quotes.unreachable]
author = "John Frusciante"
quote = "Are we down for the same cause? We don't know what we stand for. When the moments start to crack you do lose track where your head's at. And I am unreachable. What do you think when your head's full. We don't rely on what we get. We begin now where we aren't yet."



[quotes.succeeding_is_coming_together]
author = "i ching - Anonymous"
quote = "Succeeding is the coming together of all that is beautiful. Furtherance is the agreement of all that is just. Perserverance is the foundation of all actions."

